/usb_cam_node:
  ros__parameters:
    auto_white_balance: true
    autoexposure: true
    autofocus: false
    av_device_format: YUV422P
    brightness: 50
    camera_info_url: ''
    camera_name: default_cam
    contrast: -1
    exposure: 100
    focus: -1
    frame_id: default_cam
    framerate: 30.0
    gain: -1
    image_height: 480
    image_raw:
      enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/compressed
      - image_transport/raw
      - image_transport/theora
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    image_width: 640
    io_method: mmap
    pixel_format: yuyv
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    saturation: -1
    sharpness: -1
    use_sim_time: false
    video_device: /dev/video3
    white_balance: 4000

