/slam_toolbox_localization_1:
  ros__parameters:
    angle_variance_penalty: 1.0
    base_frame: base_link
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_loss_function: None
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LM
    coarse_angle_resolution: 0.0349
    coarse_search_angle_offset: 0.349
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    debug_logging: false
    distance_variance_penalty: 0.5
    do_loop_closing: true
    enable_interactive_mode: false
    fine_search_angle_offset: 0.00349
    interactive_mode: false
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    loop_search_maximum_distance: 3.0
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    map_file_name: /home/vrc/ws/src/zeus_nav/maps/rbcon_arena
    map_frame: map
    map_name: /map
    map_start_at_dock: true
    # map_start_pose: null
    map_update_interval: 10.0
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.05
    minimum_time_interval: 0.5
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    mode: localization
    odom_frame: robot1_odom
    paused_new_measurements: false
    paused_processing: false
    position_covariance_scale: 1.0
    qos_overrides:
      /parameter_eventps:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    resolution: 0.05
    scan_buffer_maximum_scan_distance: 10.0
    scan_buffer_size: 10
    scan_queue_size: 1
    scan_topic: /r1/scan
    solver_plugin: solver_plugins::CeresSolver
    tf_buffer_duration: 30.0
    throttle_scans: 1
    transform_publish_period: 0.05
    transform_timeout: 0.5
    use_map_saver: true
    use_response_expansion: true
    use_scan_barycenter: true
    use_scan_matching: true
    use_sim_time: false
    yaw_covariance_scale: 1.0


/slam_toolbox_localization_2:
  ros__parameters:
    angle_variance_penalty: 1.0
    base_frame: base_link
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_loss_function: None
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LM
    coarse_angle_resolution: 0.0349
    coarse_search_angle_offset: 0.349
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    debug_logging: false
    distance_variance_penalty: 0.5
    do_loop_closing: true
    enable_interactive_mode: false
    fine_search_angle_offset: 0.00349
    interactive_mode: false
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    loop_search_maximum_distance: 3.0
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    map_file_name: /home/vrc/ws/src/zeus_nav/maps/rbcon_arena
    map_frame: map
    map_name: /map
    map_start_at_dock: true
    # map_start_pose: null
    map_update_interval: 10.0
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.05
    minimum_time_interval: 0.5
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    mode: localization
    odom_frame: robot2_odom
    paused_new_measurements: false
    paused_processing: false
    position_covariance_scale: 1.0
    qos_overrides:
      /parameter_eventps:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    resolution: 0.05
    scan_buffer_maximum_scan_distance: 10.0
    scan_buffer_size: 10
    scan_queue_size: 1
    scan_topic: /r2/scan
    solver_plugin: solver_plugins::CeresSolver
    tf_buffer_duration: 30.0
    throttle_scans: 1
    transform_publish_period: 0.05
    transform_timeout: 0.5
    use_map_saver: true
    use_response_expansion: true
    use_scan_barycenter: true
    use_scan_matching: true
    use_sim_time: false
    yaw_covariance_scale: 1.0

