/rplidar_node:
  ros__parameters:
    angle_compensate: true
    auto_standby: false
    channel_type: serial
    flip_x_axis: false
    frame_id: laser
    inverted: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    scan_frequency: 10.0
    scan_mode: ''
    serial_baudrate: 115200
    serial_port: /dev/ttyUSB0
    tcp_ip: 192.168.0.7
    tcp_port: 20108
    topic_name: scan
    udp_ip: 192.168.11.2
    udp_port: 8089
    use_sim_time: false

